from nafld.table.processed_table import ProcessedPatientFeaturesColumns

COLUMN_NAMES_TO_DROP = [
    "ALT",
    "AST",
    "GGTP",
    "wsp_Pr",
    "INR",
    "Erytrocyty",
    "Hb",
    "leukocyty",
    "Płytki krwi",
    "mean_for_age",
    "SD_populacji",
    "centyl",
]
COLUMNS_TO_FILL_WITH_VALUES_FROM_NORMAL_DISTRIBUTION = [
    "age",
    "insulina_0",
    "HOMA_IR",
    "Z_score_BMI",
    "GPx",
    "GSH",
    "ApoE",
    "HDL",
    "ApoA1",
    "TCH",
    "TG",
    "LDL",
    "ApoB",
    "LCAT",
    "VLDL",
    "Lp(a)",
    "TBARS",
    "visceral",
    "beta_karoten",
    "visceral.1",
    "nadpowięziowy",
    "podpowięziowy",
    "wit_A",
    "wit_E",
    "proinsulina",
    "Adiponectin",
    "Leptin",
    "Lep_Recep",
    "Active IGF-1",
    "Free IGF-1",
    "Free BP-2",
    "Free BP-3",
]

TEST_SIZE_FOR_REGRESSION_MODELS = 0.1
RANDOM_STATE_FOR_REGRESSION_MODELS = 515
SEED = 300464

AGE_UNTRUSTY = 5
WEIGHT_UNTRUSTY = 40

COLNAMES_DICT_TO_TRANSLATE = {
    "ID": ProcessedPatientFeaturesColumns.PatiendId,
    "label": ProcessedPatientFeaturesColumns.Label,
    "age": ProcessedPatientFeaturesColumns.Age,
    "sex": ProcessedPatientFeaturesColumns.Sex,
    "weight": ProcessedPatientFeaturesColumns.Weight,
    "height": ProcessedPatientFeaturesColumns.Height,
    "BMI": ProcessedPatientFeaturesColumns.Bmi,
    "Z_score_BMI": ProcessedPatientFeaturesColumns.Score_BMI,
    "wątroba_powiększona": ProcessedPatientFeaturesColumns.Enlarged_liver,
    "niejednorodnie_podwyższona_echogeniczność": ProcessedPatientFeaturesColumns.Heterogeneously_increased_echogenicity,
    "zmiany_ogniskowe": ProcessedPatientFeaturesColumns.Focal_changes,
    "nadpowięziowy": ProcessedPatientFeaturesColumns.Suprafascial,
    "podpowięziowy": ProcessedPatientFeaturesColumns.Subfascial,
    "visceral": ProcessedPatientFeaturesColumns.Visceral,
    "visceral.1": ProcessedPatientFeaturesColumns.Visceral1,
    "bilirubina": ProcessedPatientFeaturesColumns.Bilirubin,
    "bil_bezpośrednia": ProcessedPatientFeaturesColumns.Bilirubin_direct,
    "wit_A": ProcessedPatientFeaturesColumns.Vit_A,
    "wit_E": ProcessedPatientFeaturesColumns.Vit_E,
    "beta_karoten": ProcessedPatientFeaturesColumns.Beta_karoten,
    "TBARS": ProcessedPatientFeaturesColumns.Tbars,
    "proinsulina": ProcessedPatientFeaturesColumns.Proinsulin,
    "insulina_0": ProcessedPatientFeaturesColumns.Insulin,
    "glukoza_0": ProcessedPatientFeaturesColumns.Glucose,
    "HOMA_IR": ProcessedPatientFeaturesColumns.Homa_Ir,
    "TCH": ProcessedPatientFeaturesColumns.Tch,
    "TG": ProcessedPatientFeaturesColumns.Tg,
    "LCAT": ProcessedPatientFeaturesColumns.Lcat,
    "ApoA1": ProcessedPatientFeaturesColumns.ApoA1,
    "ApoB": ProcessedPatientFeaturesColumns.ApoB,
    "ApoE": ProcessedPatientFeaturesColumns.ApoE,
    "Lp(a)": ProcessedPatientFeaturesColumns.Lpa,
    "LDL": ProcessedPatientFeaturesColumns.Ldl,
    "VLDL": ProcessedPatientFeaturesColumns.Vldl,
    "HDL": ProcessedPatientFeaturesColumns.Hdl,
    "GSH": ProcessedPatientFeaturesColumns.Gsh,
    "GPx": ProcessedPatientFeaturesColumns.Gpx,
    "Adiponectin": ProcessedPatientFeaturesColumns.Adiponectin,
    "Leptin": ProcessedPatientFeaturesColumns.Leptin,
    "Lep_Recep": ProcessedPatientFeaturesColumns.Lep_Recep,
    "Active IGF-1": ProcessedPatientFeaturesColumns.A_IGF1,
    "Free IGF-1": ProcessedPatientFeaturesColumns.F_IGF1,
    "Free BP-2": ProcessedPatientFeaturesColumns.F_BP2,
    "Free BP-3": ProcessedPatientFeaturesColumns.F_BP3,
    "DHA/ARA": ProcessedPatientFeaturesColumns.Dha_Ara,
    "C20:3n6/C18:3n6": ProcessedPatientFeaturesColumns.C20_3n6_C18_3n6,
    "C18:3n6/C18:2n6": ProcessedPatientFeaturesColumns.C18_3n6_C18_2n6,
    "MUFA": ProcessedPatientFeaturesColumns.Mufa,
    "SFA": ProcessedPatientFeaturesColumns.Sfa,
    "PUFA": ProcessedPatientFeaturesColumns.Pufa,
    "N3": ProcessedPatientFeaturesColumns.N3,
    "N6": ProcessedPatientFeaturesColumns.N6,
    "TRANS": ProcessedPatientFeaturesColumns.Trans,
    "n3/n6": ProcessedPatientFeaturesColumns.n3_n6,
    "C8:0": ProcessedPatientFeaturesColumns.C8,
    "C10:0": ProcessedPatientFeaturesColumns.C10,
    "C11:0": ProcessedPatientFeaturesColumns.C11,
    "C12:0": ProcessedPatientFeaturesColumns.C12,
    "C14:0": ProcessedPatientFeaturesColumns.C14,
    "C14:1 t": ProcessedPatientFeaturesColumns.C141t,
    "C14:1": ProcessedPatientFeaturesColumns.C141,
    "C15:1": ProcessedPatientFeaturesColumns.C151,
    "C16:0": ProcessedPatientFeaturesColumns.C16,
    "C16:1 t": ProcessedPatientFeaturesColumns.C161t,
    "C16:1n-7": ProcessedPatientFeaturesColumns.C161n7,
    "C17:0": ProcessedPatientFeaturesColumns.C17,
    "C17:1": ProcessedPatientFeaturesColumns.C171,
    "C18:0": ProcessedPatientFeaturesColumns.C18,
    "C18:1 t": ProcessedPatientFeaturesColumns.C181t,
    "C18:1n-9": ProcessedPatientFeaturesColumns.C181n9,
    "C18:1n-7": ProcessedPatientFeaturesColumns.C181n7,
    "C18:2 tt": ProcessedPatientFeaturesColumns.C182tt,
    "LA": ProcessedPatientFeaturesColumns.La,
    "GLA": ProcessedPatientFeaturesColumns.Gla,
    "ALA": ProcessedPatientFeaturesColumns.Ala,
    "C20:0": ProcessedPatientFeaturesColumns.C20,
    "C18:4n-3": ProcessedPatientFeaturesColumns.C184n3,
    "C20:1n-9": ProcessedPatientFeaturesColumns.C201n9,
    "C20:2n-6": ProcessedPatientFeaturesColumns.C202n6,
    "C20:3n-9": ProcessedPatientFeaturesColumns.C203n9,
    "DGLA": ProcessedPatientFeaturesColumns.Dgla,
    "AA": ProcessedPatientFeaturesColumns.Aa,
    "C20:3n-3": ProcessedPatientFeaturesColumns.C203n3,
    "C22:0": ProcessedPatientFeaturesColumns.C22,
    "C22:1 t": ProcessedPatientFeaturesColumns.C221t,
    "C22:1n-9": ProcessedPatientFeaturesColumns.C221n9,
    "EPA": ProcessedPatientFeaturesColumns.Epa,
    "C22:2n-6": ProcessedPatientFeaturesColumns.C222n6,
    "C22:4n-6": ProcessedPatientFeaturesColumns.C224n6,
    "C22:5n-6": ProcessedPatientFeaturesColumns.C225n6,
    "C24:0": ProcessedPatientFeaturesColumns.C24,
    "C24:1n-9": ProcessedPatientFeaturesColumns.C241n9,
    "C22:5n-3": ProcessedPatientFeaturesColumns.C225n3,
    "DHA": ProcessedPatientFeaturesColumns.Dha,
    "AA/DGLA": ProcessedPatientFeaturesColumns.Aa_Dgla,
    "DGLA/LA": ProcessedPatientFeaturesColumns.Dgla_La,
}
